#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Guide.Resource", IsApplication=true)]

namespace Guide
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040005
			public const int Red = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int Red2 = 2130968582;
			
			// aapt resource value: 0x7f040009
			public const int Red_10 = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int Red_49 = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int Red_Light = 2130968584;
			
			// aapt resource value: 0x7f040004
			public const int White = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int Yellow_250 = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int colorAccent = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int colorPrimary = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int colorPrimaryDark = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int Size_18 = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int guide_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int GuideFirst = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int GuideSecond = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int NoPress = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Press = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int guideText = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int point = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int viewpage = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
